// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXBT4QYtBWOg0ZoK9LFUEhwpgKfZ_kc7Y',
    appId: '1:811457496826:web:5d8504ac23a8fe6df36b43',
    messagingSenderId: '811457496826',
    projectId: 'cate-app-c3d80',
    authDomain: 'cate-app-c3d80.firebaseapp.com',
    storageBucket: 'cate-app-c3d80.appspot.com',
    measurementId: 'G-B2849E2P2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVvthqPhxpscXVTGAhBJX77GOlCBd34Ns',
    appId: '1:811457496826:android:1a705b009b1fa4f3f36b43',
    messagingSenderId: '811457496826',
    projectId: 'cate-app-c3d80',
    storageBucket: 'cate-app-c3d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMR1vxgDDoZ4XS8oFPf8shpdpLhcBVEls',
    appId: '1:811457496826:ios:e69ee303cb3c70a4f36b43',
    messagingSenderId: '811457496826',
    projectId: 'cate-app-c3d80',
    storageBucket: 'cate-app-c3d80.appspot.com',
    iosClientId:
        '811457496826-b1rud4se29p5sk0doat0bkvkv5oohneg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1788',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMR1vxgDDoZ4XS8oFPf8shpdpLhcBVEls',
    appId: '1:811457496826:ios:e69ee303cb3c70a4f36b43',
    messagingSenderId: '811457496826',
    projectId: 'cate-app-c3d80',
    storageBucket: 'cate-app-c3d80.appspot.com',
    iosClientId:
        '811457496826-b1rud4se29p5sk0doat0bkvkv5oohneg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1788',
  );
}
